version: '3.8'
services:
 dynamodb-local:
   command: "-jar DynamoDBLocal.jar -port 9000 -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   ports:
     - "9000:9000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal
